apiVersion: apps/v1
kind: ReplicaSet
metadata:
          name: frontend
          labels:
               app: mywebsite
               tier: frontend
spec:
        replicas: 2
        template:
             metadata:
                name: frontend
                labels:
                   app: mywebsite
             spec:
                 containers:
                         - name: nginx
                           image: nginx
        selector:
                matchLabels:
                   app: mywebsite
